name: Build and Test Azure Function C#

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      # - name: Test
      #   run: dotnet test --no-build --verbosity normal

      # Optional: Publish Artifact
      # - name: Publish Build Artifacts
      #   if: success()
      #   run: dotnet publish --configuration Release --output ./publish

      # Optional: Upload artifact
      # - name: Upload publish folder
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: azure-function-app
      #     path: ./publish
